default: &default
  corpid: "corpid"
  corpsecret: "corpsecret"
  agentid:  1
# Or if using public account, only need above two line
#  appid: "my_appid"
#  secret: "my_secret"
  token:    "my_token"
  access_token: "C:/Users/[username]/wechat_access_token"
  encrypt_mode: false # if true must fill encoding_aes_key
  encoding_aes_key:  "my_encoding_aes_key"
  jsapi_ticket: "C:/Users/[user_name]/wechat_jsapi_ticket"

production:
  # corpid:     "wx47b02e6b45bf1dad"
  # corpsecret: "b78a5266c57391d8bd7bce75e86fc3c0"
  # agentid:    <%= ENV['WECHAT_AGENTID'] %>
# Or if using public account, only need above two line
  appid:      "wx47b02e6b45bf1dad"
  secret:     "b78a5266c57391d8bd7bce75e86fc3c0"
  token:      "cloud_closet"
  timeout:    30,
  skip_verify_ssl: false
  # access_token:  "./"
  encrypt_mode: false # if true must fill encoding_aes_key
  encoding_aes_key:  "FKX3mHXPDwRwMd0ezFK519ALxcK0dmKbj7faDt23heA"
  # jsapi_ticket: <%= ENV['WECHAT_JSAPI_TICKET'] %>
  # oauth2_cookie_duration: <%= ENV['WECHAT_OAUTH2_COOKIE_DURATION'] %> # seconds

development:
  <<: *default
  trusted_domain_fullname: "http://your_dev.proxy.qqbrowser.cc"

test:
  <<: *default